import { addCollection, type IconifyJSON } from "@iconify/react";
import iconData from "./iconData.json";

// Every icon the app uses ships in the bundle (generated by scripts/build-icons.mjs),
// so <Icon> renders synchronously and never calls the Iconify API.
for (const collection of iconData as unknown as IconifyJSON[]) addCollection(collection);
