-- ============================================================================
-- Baseline: the schema as it existed in production on 2026-09-24, before any
-- tracked migrations. It was built by hand in the Supabase dashboard; this
-- file reconstructs it from the live catalog so a fresh database (local dev,
-- branch) can be brought to the same starting point.
--
-- It is NOT applied to production (production already has this state).
-- Later migrations in this folder describe every change since.
-- ============================================================================

-- ─── Tables ─────────────────────────────────────────────────────────────────
create table public.profiles (
  id uuid not null,
  created_at timestamp with time zone default now(),
  first_name text,
  last_name text,
  avatar_url text,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade
);

create table public.groups (
  id uuid default gen_random_uuid() not null,
  name text not null,
  share_code text,
  created_by uuid,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  avatar_url text,
  constraint groups_pkey primary key (id),
  constraint groups_share_code_key unique (share_code),
  constraint groups_created_by_fkey foreign key (created_by) references auth.users(id) on delete cascade
);

create table public.group_members (
  group_id uuid not null,
  user_id uuid not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint group_members_pkey primary key (group_id, user_id),
  constraint group_members_group_id_fkey foreign key (group_id) references public.groups(id) on delete cascade,
  constraint group_members_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade
);

create sequence public.restaurants_id_seq;
create table public.restaurants (
  id integer default nextval('restaurants_id_seq'::regclass) not null,
  owner text not null,
  place_id text not null,
  name text not null,
  address text not null,
  latitude text not null,
  longitude text not null,
  rating text,
  user_rating_count integer,
  price_level text,
  primary_type text,
  photo_url text,
  website_url text,
  booking_platform text,
  booking_url text,
  vibes text default '[]'::text not null,
  notes text default ''::text,
  visited boolean default false not null,
  user_score integer,
  visit_photo_url text,
  visited_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  group_id uuid not null,
  opening_hours jsonb,
  last_synced_at timestamp with time zone default now(),
  constraint restaurants_pkey primary key (id),
  constraint restaurants_group_id_fkey foreign key (group_id) references public.groups(id) on delete cascade
);
alter sequence public.restaurants_id_seq owned by public.restaurants.id;

create table public.reviews (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  score integer,
  notes text,
  photo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  photo_urls text[] default '{}'::text[],
  place_id character varying(255) not null,
  constraint reviews_pkey primary key (id),
  constraint reviews_user_id_fkey foreign key (user_id) references auth.users(id)
);
create index idx_reviews_place_id on public.reviews using btree (place_id);

-- ─── Row level security ─────────────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.restaurants enable row level security;
alter table public.reviews enable row level security;

create policy "Profiles are viewable by everyone" on public.profiles for select to authenticated using (true);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

create policy "View groups you belong to" on public.groups for all
  using (exists (select 1 from public.group_members where group_members.group_id = groups.id and group_members.user_id = auth.uid()));

create policy "View group members" on public.group_members for select using (true);
create policy "Insert group members" on public.group_members for insert with check (user_id = auth.uid());
create policy "Delete group members" on public.group_members for delete using (user_id = auth.uid());

create policy "Users can insert own restaurants" on public.restaurants for insert with check (owner = (auth.uid())::text);
create policy "Workspace Members can view restaurants" on public.restaurants for select
  using (group_id in (select group_members.group_id from public.group_members where group_members.user_id = auth.uid()));
create policy "Workspace Members can insert restaurants" on public.restaurants for insert
  with check (group_id in (select group_members.group_id from public.group_members where group_members.user_id = auth.uid()));
create policy "Workspace Members can update restaurants" on public.restaurants for update
  using (group_id in (select group_members.group_id from public.group_members where group_members.user_id = auth.uid()));
create policy "Workspace Members can delete restaurants" on public.restaurants for delete
  using (group_id in (select group_members.group_id from public.group_members where group_members.user_id = auth.uid()));

create policy "Universal Review Visibility" on public.reviews for select to authenticated using (true);
create policy "Users can manage their own reviews" on public.reviews for all using (auth.uid() = user_id);

-- ─── Functions ──────────────────────────────────────────────────────────────
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to '' as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (new.id, new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name');
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.create_group(group_name text)
returns uuid language plpgsql security definer as $$
declare
  new_id uuid;
  new_code text;
begin
  new_code := upper(substring(md5(random()::text) from 1 for 6));
  insert into public.groups (name, share_code, created_by) values (group_name, new_code, auth.uid()) returning id into new_id;
  insert into public.group_members (group_id, user_id) values (new_id, auth.uid());
  return new_id;
end;
$$;

create or replace function public.join_group(invite_code text)
returns void language plpgsql security definer as $$
declare
  target_group_id uuid;
begin
  select id into target_group_id from public.groups where share_code = invite_code;
  if target_group_id is null then
    raise exception 'Invalid share code. Please double check with your friend!';
  end if;
  insert into public.group_members (group_id, user_id) values (target_group_id, auth.uid()) on conflict do nothing;
end;
$$;

create or replace function public.delete_user_account()
returns void language plpgsql security definer as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;

create or replace function public.check_and_update_visited_status(p_restaurant_id integer)
returns boolean language plpgsql security definer as $$
declare
  v_group_id uuid; v_place_id text; v_member_count int; v_review_count int; v_consensus boolean;
begin
  select group_id, place_id into v_group_id, v_place_id from public.restaurants where id = p_restaurant_id;
  if v_group_id is null then
    update public.restaurants set visited = true where id = p_restaurant_id;
    return true;
  end if;
  select count(distinct user_id) into v_member_count from public.group_members where group_id = v_group_id;
  select count(distinct r.user_id) into v_review_count from public.reviews r
    join public.group_members gm on r.user_id = gm.user_id
    where r.place_id = v_place_id and gm.group_id = v_group_id;
  v_consensus := v_member_count > 0 and v_review_count >= v_member_count;
  update public.restaurants set visited = v_consensus where id = p_restaurant_id;
  return v_consensus;
end;
$$;

create or replace function public.get_random_restaurant(p_group_id uuid default null)
returns setof public.restaurants language plpgsql as $$
begin
  if p_group_id is not null then
    return query select * from public.restaurants where group_id = p_group_id order by random() limit 1;
  else
    return query select * from public.restaurants order by random() limit 1;
  end if;
end;
$$;

-- link_partner(code text) and unlink_partner() also existed; they referenced
-- profiles.share_code / profiles.partner_id, which no longer exist, so they
-- could not run. Omitted here; dropped in the security migration.

-- ─── Realtime ───────────────────────────────────────────────────────────────
alter publication supabase_realtime add table public.restaurants, public.reviews, public.groups, public.group_members, public.profiles;

-- ─── Storage ────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public) values
  ('photos', 'photos', true),
  ('place_photos', 'place_photos', true),
  ('avatars', 'avatars', true)
on conflict (id) do nothing;

create policy "Allow Auth Uploads" on storage.objects for insert to authenticated with check (bucket_id = 'avatars');
create policy "Allow Auth Updates" on storage.objects for update to authenticated using (bucket_id = 'avatars');
create policy "Allow authenticated uploads" on storage.objects for insert to authenticated with check (bucket_id = 'place_photos');
create policy "Allow public read access" on storage.objects for select using (bucket_id = 'place_photos');
create policy "Auth users can insert photos" on storage.objects for insert to authenticated with check (bucket_id = 'photos');
create policy "Authenticated users can upload photos" on storage.objects for insert to authenticated with check (bucket_id = 'photos');
create policy "Authenticated users can update photos" on storage.objects for update to authenticated using (bucket_id = 'photos');
create policy "Auth users can delete photos" on storage.objects for delete to authenticated using (bucket_id = 'photos');
create policy "Authenticated users can delete photos" on storage.objects for delete to authenticated using (bucket_id = 'photos');
